[package]
name = "aoc2024_day16"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc2024_utils = { path = "../utils" }
num = "0.4.0"
itertools = "0.13.0"
rustc-hash = "2.1.0"
petgraph = "0.6.5"

[[bin]]
name = "day16"
path = "main.rs"
