[package]
name = "aoc2024_day13"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc2024_utils = { path = "../utils" }
nalgebra = "0.33.2"
itertools = "0.13.0"

[[bin]]
name = "day13"
path = "main.rs"
